# Default values for Task Management frontend
replicaCount: 1

image:
  repository: taskmanagement-frontend
  tag: "latest"
  pullPolicy: IfNotPresent

# Leave empty if container runtime is already authenticated with Harbor
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5

env: []
  # - name: ENV_VAR_NAME
  #   value: "value"
